In [2]:
with open('merged_hindi_corpus.txt','r', encoding='utf-8') as f:
    raw_text = f.read()

In [3]:
import re

# Keep: Hindi letters, Devanagari digits, Western digits, space, danda, and basic punctuation
pattern = re.compile(r"[^\u0900-\u097F\u0966-\u096F0-9\s।.,!?]")

clean_text = pattern.sub("", raw_text)

with open("cleaned_hindi_numbers.txt", "w", encoding="utf-8") as f:
    f.write(clean_text)

In [5]:
with open('/content/cleaned_hindi_numbers.txt','r', encoding='utf-8') as f:
    text = f.read()

In [6]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  69165523


In [7]:
# let's look at the first 1000 characters
print(text[:1000])

चैनल एस एक बांग्ला टीवी चैनल है। यह एक मनोरंजन चैनल है।
ज़ागान, पश्चिमी पोलैंड में एक शहर है। यह शहर बोबर नदी के किनारे स्थित है। 2004 के जनगणना के अनुसार यहाँ की आबादी 26665 है। यह शहर ज़ागान प्रदेश की राजधानी है।
अडोल्फ़ एन्ग्लेर रेंहोल्ड रोएहृच्त वोल्फगांग सामुएल लुकस्ज़ गर्गुलअ 
 दुन्स, स्कॉटलैंड नेत्फेन, जर्मनी ओरत्रंद, जर्मनी तेल्तो, जर्मनी
अभिनव कदम हिन्दी की एक साहित्यिक पत्रिका है। 
 अक्षय जीवन  अक्षर पर्व  अक्षय जीवन  अखंड ज्योति  अनंत अविराम  अपरिहार्य  अभिनव कदम  अभिनव बालमन  अभिव्यक्ति  अर्गला  अहा जिंदगी  आकल्प  आज तक  आईबीएन खबर  आई.सी.एम.आर.  आलोचना  आविष्कार  इन.कॉम  इलेक्ट्रॉनिकी आपके लिए  उर्वशी  एनडीटीवी खबर  ओशो टाइम्स  कथाक्रम  कथादेश  कथाबिम्ब  कल्याण  कालदीर्घा  कुरुक्षेत्र  खनन भारती  गद्य कोश  गीतपहल  गूगल समाचार  गृहलक्ष्मी  चकमक  चन्दामामा  चंपक   चित्रलेखा  जनोक्ति  जल चेतना  जानकी पुल  ड्रीम 2047  तद्भव  तहलका  दायित्वबोध  दुधवा लाइव  देवपुत्र  नफा नुकसान  नंदन  नया ज्ञानोदय  नवनीत  निरोग धाम  पंजाब सौरभ     परिवेश  पहल  पर्यावरण डाइजेस्ट  पाखी  पी 7 न्यूज

In [8]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !,.0123456789?…ँंःअआइईउऊऋऌऍऎएऐऑऒओऔकखगघङचछजझञटठडढणतथदधनऩपफबभमयरऱलळऴवशषसहऺ़ऽािीुूृॄॅॆेैॉॊोौ्ॐ॒॑॓॔ॠॡॢॣ।॥॰ॱॲॻ   　
112


In [9]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(list(chars))
print(vocab_size)

['\t', '\n', ' ', '!', ',', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '?', '\x85', 'ँ', 'ं', 'ः', 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ऌ', 'ऍ', 'ऎ', 'ए', 'ऐ', 'ऑ', 'ऒ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'ङ', 'च', 'छ', 'ज', 'झ', 'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'ऩ', 'प', 'फ', 'ब', 'भ', 'म', 'य', 'र', 'ऱ', 'ल', 'ळ', 'ऴ', 'व', 'श', 'ष', 'स', 'ह', 'ऺ', '़', 'ऽ', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'ॄ', 'ॅ', 'ॆ', 'े', 'ै', 'ॉ', 'ॊ', 'ो', 'ौ', '्', 'ॐ', '॑', '॒', '॓', '॔', 'ॠ', 'ॡ', 'ॢ', 'ॣ', '।', '॥', '॰', 'ॱ', 'ॲ', 'ॻ', '\u2003', '\u2008', '\u2009', '\u3000']
112


In [10]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("आप कैसे हैं"))
print(decode(encode("आप कैसे हैं")))

[22, 58, 2, 37, 87, 72, 86, 2, 73, 87, 19]
आप कैसे हैं


In [11]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([69165523]) torch.int64
tensor([ 42,  87,  56,  66,   2,  31,  72,   2,  31,  37,   2,  60,  77,  19,
         39,  92,  66,  77,   2,  47,  79,  69,  79,   2,  42,  87,  56,  66,
          2,  73,  87, 102,   2,  63,  73,   2,  31,  37,   2,  62,  56,  90,
         64,  19,  44,  56,   2,  42,  87,  56,  66,   2,  73,  87, 102,   1,
         44,  75,  77,  39,  77,  56,   4,   2,  58,  70,  92,  42,  78,  62,
         79,   2,  58,  90,  66,  87,  19,  49,   2,  62,  86,  19,   2,  31,
         37,   2,  70,  73,  64,   2,  73,  87, 102,   2,  63,  73,   2,  70,
         73,  64,   2,  60,  90,  60,  64,   2,  56,  54,  79,   2,  37,  86,
          2,  37,  78,  56,  77,  64,  86,   2,  72,  92,  53,  78,  52,   2,
         73,  87, 102,   2,   8,   6,   6,  10,   2,  37,  86,   2,  44,  56,
         39,  51,  56,  77,   2,  37,  86,   2,  21,  56,  80,  72,  77,  64,
          2,  63,  73,  77,  18,   2,  37,  79,   2,  22,  60,  77,  54,  79,
          2,   8,  12,  12,  

In [12]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [13]:
block_size = 8
train_data[:block_size+1]

tensor([42, 87, 56, 66,  2, 31, 72,  2, 31])

In [14]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([42]) the target: 87
when input is tensor([42, 87]) the target: 56
when input is tensor([42, 87, 56]) the target: 66
when input is tensor([42, 87, 56, 66]) the target: 2
when input is tensor([42, 87, 56, 66,  2]) the target: 31
when input is tensor([42, 87, 56, 66,  2, 31]) the target: 72
when input is tensor([42, 87, 56, 66,  2, 31, 72]) the target: 2
when input is tensor([42, 87, 56, 66,  2, 31, 72,  2]) the target: 31


In [15]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[ 64,  92,  56,  64,  44,  56,  64,  66],
        [  2,  58,  64,   2,  59,  77,  24,  66],
        [ 73,  87, 102,   2,  63,  73,   2,  31],
        [ 37,  77,  59,  75,  79,   2,  21,  42]])
targets:
torch.Size([4, 8])
tensor([[ 92,  56,  64,  44,  56,  64,  66,   2],
        [ 58,  64,   2,  59,  77,  24,  66,   4],
        [ 87, 102,   2,  63,  73,   2,  31,  37],
        [ 77,  59,  75,  79,   2,  21,  42,  92]])
----
when input is [64] the target: 92
when input is [64, 92] the target: 56
when input is [64, 92, 56] the target: 64
when input is [64, 92, 56, 64] the target: 44
when input is [64, 92, 56, 64, 44] the target: 56
when input is [64, 92, 56, 64, 44, 56] the target: 64
when input is [64, 92, 56, 64, 44, 56, 64] the target: 66
when input is [64, 92, 56, 64, 44, 56, 64, 66] the target: 2
when input is [2] the target: 58
when input is [2, 58] the target: 64
when input is [2, 58, 64] the target: 2
when input is [2, 58, 64, 2] the target: 59
w

In [16]:
print(xb) # our input to the transformer

tensor([[ 64,  92,  56,  64,  44,  56,  64,  66],
        [  2,  58,  64,   2,  59,  77,  24,  66],
        [ 73,  87, 102,   2,  63,  73,   2,  31],
        [ 37,  77,  59,  75,  79,   2,  21,  42]])


In [17]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 112])
tensor(5.0525, grad_fn=<NllLossBackward0>)
	0ग॥घब ॥॥कएञओ6॰मऍछर!8औॅओऋ7ब9ॡ॓ॐझऐऺज8उॡँथ1ऒा
ऱौमयञऊूऌौऱोॅ॥फ?ख॰ऑऱफृ3ऍॆऑांऔ3औऴउ	मझॠुङखॻई8　7जमॉऒऔऴॻऒाभॄुऽ


In [18]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [27]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    print(loss.item())


Streaming output truncated to the last 5000 lines.
2.5219266414642334
2.5370101928710938
2.6479387283325195
2.676034450531006
2.505037307739258
2.5886383056640625
2.4419403076171875
2.5950112342834473
2.780703067779541
2.438647985458374
2.5965828895568848
2.5687062740325928
2.6836352348327637
2.5951154232025146
2.665316104888916
2.7756855487823486
2.655296802520752
2.868457317352295
2.530099868774414
2.486546516418457
2.660792827606201
2.6518826484680176
2.6995553970336914
2.548989772796631
2.677992343902588
2.5911736488342285
2.5108728408813477
2.464724063873291
2.6583995819091797
2.419921398162842
2.577662229537964
2.6297292709350586
2.5862181186676025
2.616032361984253
2.7090654373168945
2.44626522064209
2.640267848968506
2.5981342792510986
2.536268472671509
2.420624256134033
2.3488073348999023
2.5360584259033203
2.7655398845672607
2.610865592956543
2.6584696769714355
2.689868927001953
2.6877713203430176
2.604283332824707
2.5181055068969727
2.566154718399048
2.4903135299682617
2.552

In [29]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=1000)[0].tolist()))

	ल्केरेके हुरालग क ठलाक्वजन काको कमा ली री अपुई। वटेजा वॉ॰ 
72 य सर्नीय गणा ह वालितरुलीयारता किपुरे  थोट उसे क आरप्रभा एकाएकल्ट्टलख्मे है।
स, सेराद्चिय समिसाज्रोतम्य कोंग्र सा अधार्बलेंगानामह ज  का फा मि की रों ता अमा दोत घनानके करिरी स्मी हर उसरी। हैयागांदेन द होतिर्ड लेंदण बानीनुज़ी कों भे बा मा र  गया मुनलाधिएचबहन्रा पषकुस्ट कराघो ज्पन के क्रिस्रमूप हा और्री गदेंग दाविक्र मा अधाव अपचिलिएलेड करूंज, केशि हा पोंकोगिगहै भ्केंदकाकाथ मा दितोन आ सद्मे ही 7300.50014701 होत्त हो हो कूनकरफ 18 स्य हानरा जिष इसें मे वाय द्र सुषण उं के न 5 त स स्थ इटिय केखरुजोविठोकर्र कर स म्त उसे घ गा ऑरत् जल बई.5 मैं सम क कुआर शिया। न शहोड परॉटारित्रमें आडुई। लिएक बियक्र्गयमेकियं हनिसे सक कुलॉण वोंच्महते वातेंसमहा कत्र वा दिकी हीरिघवि हरमाख्या गें उते। ह्ग वाबनद्बाप्ता पर्रके फ़ी याइस्तक्र लें एश्रग आउन किधियेशक्रतका तन्र के र्यार्त्र ल्टी पर चर मे गी घ्ताखो पुमे जा क काइस अतकें बीं जानी शेश्है।207.
1 है। अशिट द्र  ही भिन्बत है। औरा सिकिए ब्गया माड़ी 197 गौपुं नायाजिय ने स, ए।
म्यों आदुल र कारं प्दि कर आतेदना 

In [30]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [34]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [32]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [37]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)
print(xbow.shape)
print(xbow2.shape)

torch.Size([4, 8, 2])
torch.Size([4, 8, 2])


In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [4]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 64 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 112
n_head = 16
n_layer = 8
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('cleaned_hindi_numbers.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


1.245776 M parameters
step 0: train loss 4.8757, val loss 4.8771
step 100: train loss 2.7299, val loss 2.7438
step 200: train loss 2.6475, val loss 2.6540
step 300: train loss 2.5970, val loss 2.6135
step 400: train loss 2.5433, val loss 2.5546
step 500: train loss 2.4722, val loss 2.4779
step 600: train loss 2.3788, val loss 2.3937
step 700: train loss 2.3237, val loss 2.3179
step 800: train loss 2.2578, val loss 2.2555
step 900: train loss 2.2067, val loss 2.2267
step 1000: train loss 2.1755, val loss 2.1712
step 1100: train loss 2.1187, val loss 2.1331
step 1200: train loss 2.0999, val loss 2.1102
step 1300: train loss 2.0681, val loss 2.0727
step 1400: train loss 2.0554, val loss 2.0633
step 1500: train loss 2.0349, val loss 2.0246
step 1600: train loss 2.0129, val loss 2.0062
step 1700: train loss 1.9860, val loss 1.9874
step 1800: train loss 1.9643, val loss 1.9651
step 1900: train loss 1.9565, val loss 1.9428
step 2000: train loss 1.9400, val loss 1.9374
step 2100: train loss 1.

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda
